// SPEC.md §12's document, laid out onto a page — against a recording canvas
// rather than a real one.
//
// The port is the point. A PDF library is a dependency that has to be audited
// for a network path (SPEC.md §2), and the LAYOUT decisions — which rows go on
// which page, where the repeating header goes, which edge the date column sits
// against in Persian — are decisions this app makes, not ones a library makes
// for it. Putting them behind an interface means they can be asserted here, in
// milliseconds, and that swapping the library later cannot silently move them.
@TestOn('vm')
library;

import 'package:odova/core/domain/enums.dart';
import 'package:odova/core/domain/models/records.dart';
import 'package:odova/core/domain/models/vehicle.dart';
import 'package:odova/core/due/reading_series.dart';
import 'package:odova/core/ids/record_id.dart';
import 'package:odova/core/money/currency.dart';
import 'package:odova/core/money/money.dart';
import 'package:odova/core/report/pdf_canvas.dart';
import 'package:odova/core/report/service_report.dart';
import 'package:odova/core/report/service_report_pdf.dart';
import 'package:odova/core/report/service_report_writer.dart';
import 'package:odova/core/time/civil_date.dart';
import 'package:odova/core/units/distance.dart';
import 'package:test/test.dart';

const _ulid = '01JQ8ZK3M7F0R6XN2E9TB4HCVD';
const _abc = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
String _b(int i) =>
    '${_ulid.substring(0, 24)}${_abc[i ~/ 32 % 32]}${_abc[i % 32]}';
CivilDate day(String t) => CivilDate.tryParse(t)!;
final Currency _eur = Currency.tryParse('EUR')!;
final VehicleId _veh = VehicleId.tryParse('veh_${_b(0)}')!;

/// A canvas that records instead of drawing.
class RecordingCanvas implements PdfCanvas {
  final List<PdfPageSpec> pages = [];
  final List<(int page, String text, PdfSlot slot)> texts = [];

  /// A LIST, not a set. A set records "which fonts" and silently swallows
  /// "how many times" — which is exactly the assertion §12's "embedded once"
  /// needs, and the first version of this fake used a set and could not fail.
  final List<String> embedCalls = [];
  int _page = -1;

  @override
  void beginPage(PdfPageSpec spec) {
    pages.add(spec);
    _page++;
  }

  @override
  void drawText(String text, {required PdfSlot slot}) =>
      texts.add((_page, text, slot));

  @override
  void embedFont(String family) => embedCalls.add(family);

  List<String> textsOn(int page) => [
    for (final t in texts)
      if (t.$1 == page) t.$2,
  ];

  List<String> textsIn(PdfSlot slot) => [
    for (final t in texts)
      if (t.$3 == slot) t.$2,
  ];
}

ServiceRecord record(int i) => ServiceRecord(
  id: ServiceRecordId.tryParse('srv_${_b(i)}')!,
  vehicleId: _veh,
  occurredOn: '2026-${(i % 12 + 1).toString().padLeft(2, '0')}-14',
  odometer: Distance.fromKm(100000 + i * 500),
  odometerUnit: DistanceUnit.km,
  vendor: 'Werkstatt Krüger',
  lines: [
    ServiceLine(
      id: ServiceLineId.tryParse('lin_${_b(i)}')!,
      serviceRecordId: ServiceRecordId.tryParse('srv_${_b(i)}')!,
      label: 'Oil and filter',
      amount: Money(18450, _eur),
    ),
  ],
  createdAtUtcMs: 1,
  updatedAtUtcMs: 1,
);

ServiceReportDocument doc({int records = 3, String? vin, String? plate}) =>
    buildServiceReport(
      vehicle: Vehicle(
        id: _veh,
        name: 'VW Golf',
        vehicleType: VehicleType.car,
        fuelKindDefault: FuelKind.diesel,
        status: VehicleStatus.active,
        vin: vin,
        plate: plate,
        createdAtUtcMs: 1,
        updatedAtUtcMs: 1,
      ),
      records: [for (var i = 1; i <= records; i++) record(i)],
      items: const [],
      series: ReadingSeries.from(const [], const []),
      options: ServiceReportOptions(plateAndVin: vin != null || plate != null),
      today: day('2026-09-02'),
    );

RecordingCanvas write(
  ServiceReportDocument document, {
  PaperSize paper = PaperSize.a4,
  bool rtl = false,
  String scriptFamily = 'Inter',
}) {
  final canvas = RecordingCanvas();
  writeServiceReportPdf(
    document,
    canvas: canvas,
    paper: paper,
    rtl: rtl,
    scriptFamily: scriptFamily,
    strings: const ServiceReportPdfStrings(
      title: 'Service history',
      pageOf: 'Page {n} of {total}',
      columnDate: 'Date',
      columnOdometer: 'Odometer',
      columnWork: 'What was done',
      columnCost: 'Cost',
      footer: 'Generated by Odova on {date} ({iso}).',
      estimatedFootnote: '~ odometer estimated at the time.',
    ),
    formatDate: (d) => d,
    formatDistance: (d, {required estimated}) =>
        '${estimated ? '~' : ''}${d.metres ~/ 1000} km',
    formatMoney: (m) => '${m.amountMinor / 100} ${m.currency.code}',
  );
  return canvas;
}

void main() {
  test('every page carries the paper size it was asked for', () {
    final canvas = write(doc(records: 60), paper: PaperSize.usLetter);

    expect(canvas.pages, isNotEmpty);
    expect(
      canvas.pages.every((p) => p.paper == PaperSize.usLetter),
      isTrue,
      reason: 'a document that changes paper mid-way prints wrong on both',
    );
  });

  test('the table header repeats on EVERY page', () {
    // §12: "Multi-page, repeating table header." A reader who turns to page
    // four sees four columns of numbers with nothing saying which is the
    // odometer and which is the cost.
    final canvas = write(doc(records: 60));

    expect(canvas.pages.length, greaterThan(1));
    for (var p = 0; p < canvas.pages.length; p++) {
      expect(
        canvas.textsOn(p),
        contains('Odometer'),
        reason: 'page ${p + 1} has no column header',
      );
    }
  });

  test('the footer carries "Page 2 of 4" with both numbers filled', () {
    final canvas = write(doc(records: 60));
    final total = canvas.pages.length;

    expect(canvas.textsOn(1), contains('Page 2 of $total'));
    expect(
      canvas.textsIn(PdfSlot.pageNumber),
      hasLength(total),
      reason: 'one per page, none missing',
    );
  });

  test('34 services produce 2 to 3 pages and 200 about 12', () {
    // §12's own figures, asserted through the writer rather than only through
    // the paginator — so a writer that ignored the budget would be caught.
    expect(write(doc(records: 34)).pages.length, inInclusiveRange(2, 3));
    expect(write(doc(records: 200)).pages.length, inInclusiveRange(10, 14));
  });

  test('every record reaches a page; none is dropped at a boundary', () {
    // The classic paginator bug: the row that would have been the first of a
    // new page falls between the two loops and vanishes. A service missing
    // from a document handed to a buyer is the worst possible instance of it.
    final canvas = write(doc(records: 47));
    final odometers = canvas.textsIn(PdfSlot.recordOdometer);

    expect(odometers.toSet(), hasLength(47));
  });

  test('the unremovable footer is on the LAST page', () {
    final canvas = write(doc(records: 60));

    expect(
      canvas.textsOn(canvas.pages.length - 1),
      contains('Generated by Odova on 2026-09-02 (2026-09-02).'),
    );
  });

  test(
    'the footer date carries the ISO Gregorian alongside the display one',
    () {
      // §12: "… on ۱۱ شهریور ۱۴۰۵ (2026-09-02) …". A Jalali date alone is
      // unreadable to the buyer's insurer, and an ISO date alone is unreadable
      // to the seller.
      final canvas = RecordingCanvas();
      writeServiceReportPdf(
        doc(),
        canvas: canvas,
        paper: PaperSize.a4,
        rtl: true,
        scriptFamily: 'Vazirmatn',
        strings: const ServiceReportPdfStrings(
          title: 'تاریخچه سرویس',
          pageOf: 'صفحه {n} از {total}',
          columnDate: 'تاریخ',
          columnOdometer: 'کیلومتر',
          columnWork: 'کار انجام‌شده',
          columnCost: 'هزینه',
          footer: 'ساخته‌شده در {date} ({iso}).',
          estimatedFootnote: '~ تخمینی.',
        ),
        formatDate: (d) => '۱۱ شهریور ۱۴۰۵',
        formatDistance: (d, {required estimated}) => '۱۰۰٬۰۰۰',
        formatMoney: (m) => '۱۸۴',
      );

      expect(
        canvas.textsIn(PdfSlot.footer).single,
        'ساخته‌شده در ۱۱ شهریور ۱۴۰۵ (2026-09-02).',
      );
    },
  );

  group('right-to-left', () {
    test('the page direction is RTL and the date column moves to the end', () {
      // §12: "page direction RTL, table columns reversed (date at the right
      // edge)". The writer emits logical START/END slots and the page's
      // direction decides which physical edge that is — the alternative is a
      // writer that knows about left and right, which is what §5 forbids.
      final canvas = write(doc(), rtl: true);

      expect(canvas.pages.every((p) => p.rtl), isTrue);
    });

    test('a VIN is forced LTR even on an RTL page', () {
      // §12: "VIN is forced LTR with start-of-line alignment even on an RTL
      // page." A VIN is a serial number; mirrored, it is a different serial
      // number, and it is the field a buyer types into a history check.
      final canvas = write(doc(vin: 'WVWZZZ1KZAW000001'), rtl: true);

      expect(canvas.textsIn(PdfSlot.vin), ['WVWZZZ1KZAW000001']);
      expect(
        canvas.texts.firstWhere((t) => t.$3 == PdfSlot.vin).$2,
        isNot(contains('\u202B')),
        reason: 'no RTL embedding character pushed onto it',
      );
    });

    test('a plate prints verbatim and is never digit-shaped', () {
      // §12: "a plate is a picture of a plate, not a number." Shaping
      // `M-AB 1234` to Persian digits produces a plate that does not exist.
      final canvas = write(doc(plate: 'M-AB 1234'), rtl: true);

      expect(canvas.textsIn(PdfSlot.plate), ['M-AB 1234']);
    });
  });

  group('fonts', () {
    test(
      'an Arabic-script document EMBEDS its family, never references it',
      () {
        // §12: "embedded, not referenced, because the file must render on a
        // stranger's phone." A buyer opening this in a desktop viewer with no
        // Persian font sees boxes, and concludes the seller sent a broken file.
        final canvas = RecordingCanvas();
        writeServiceReportPdf(
          doc(),
          canvas: canvas,
          paper: PaperSize.a4,
          rtl: true,
          scriptFamily: 'Vazirmatn',
          strings: const ServiceReportPdfStrings(
            title: 'ت',
            pageOf: '{n}/{total}',
            columnDate: 'ت',
            columnOdometer: 'ک',
            columnWork: 'ک',
            columnCost: 'ه',
            footer: '{date} ({iso})',
            estimatedFootnote: '~',
          ),
          formatDate: (d) => d,
          formatDistance: (d, {required estimated}) => '1',
          formatMoney: (m) => '1',
        );

        expect(canvas.embedCalls, contains('Vazirmatn'));
      },
    );

    test('the font is embedded once, not once per page', () {
      // §12 ships a Vazirmatn subset; embedding it on each of twelve pages is
      // a twelve-fold file for a document nobody reads twice, and it is the
      // natural shape if the embed call sits inside the page loop.
      final canvas = write(doc(records: 60));

      expect(canvas.pages.length, greaterThan(1), reason: 'several pages');
      expect(canvas.embedCalls, hasLength(1));
    });
  });
}
