// SPEC.md §12: "Copy as text — the same content as plain text on the
// clipboard, for pasting into a classifieds listing, which is how cars are
// actually sold on Divar, Willhaben, Leboncoin and Marketplace."
//
// "The same content" is the whole specification and the whole risk. A text
// renderer that drifts from the PDF produces two documents from one model, and
// the one the seller pastes into an advert is the one nobody proof-read. So
// this renders from `ServiceReportDocument` and from nothing else — the same
// object the preview and the PDF read — and the tests below assert the
// toggles and the exclusions reach it identically.
@TestOn('vm')
library;

import 'package:odova/core/domain/enums.dart';
import 'package:odova/core/domain/models/records.dart';
import 'package:odova/core/domain/models/vehicle.dart';
import 'package:odova/core/due/reading_series.dart';
import 'package:odova/core/ids/record_id.dart';
import 'package:odova/core/money/currency.dart';
import 'package:odova/core/money/money.dart';
import 'package:odova/core/report/service_report.dart';
import 'package:odova/core/report/service_report_text.dart';
import 'package:odova/core/time/civil_date.dart';
import 'package:odova/core/units/distance.dart';
import 'package:test/test.dart';

const _ulid = '01JQ8ZK3M7F0R6XN2E9TB4HCVD';
const _alphabet = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
String _b(int i) =>
    '${_ulid.substring(0, 24)}${_alphabet[i ~/ 32 % 32]}${_alphabet[i % 32]}';
CivilDate day(String t) => CivilDate.tryParse(t)!;
final Currency _eur = Currency.tryParse('EUR')!;
final VehicleId _veh = VehicleId.tryParse('veh_${_b(0)}')!;

ServiceRecord record(
  int i, {
  required String on,
  required int km,
  int c = 18450,
}) => ServiceRecord(
  id: ServiceRecordId.tryParse('srv_${_b(i)}')!,
  vehicleId: _veh,
  occurredOn: on,
  odometer: Distance.fromKm(km),
  odometerUnit: DistanceUnit.km,
  vendor: 'Werkstatt Krüger',
  lines: [
    ServiceLine(
      id: ServiceLineId.tryParse('lin_${_b(i)}')!,
      serviceRecordId: ServiceRecordId.tryParse('srv_${_b(i)}')!,
      label: 'Oil and filter',
      amount: Money(c, _eur),
    ),
  ],
  createdAtUtcMs: 1,
  updatedAtUtcMs: 1,
);

String render({
  ServiceReportOptions options = const ServiceReportOptions(),
  String? plate,
  String? notes,
  List<ServiceRecord>? records,
}) {
  final doc = buildServiceReport(
    vehicle: Vehicle(
      id: _veh,
      name: 'VW Golf 1.6 TDI',
      vehicleType: VehicleType.car,
      fuelKindDefault: FuelKind.diesel,
      status: VehicleStatus.active,
      plate: plate,
      notes: notes,
      purchaseDate: '2018-03-04',
      purchaseOdometer: const Distance.fromKm(62400),
      createdAtUtcMs: 1,
      updatedAtUtcMs: 1,
    ),
    records: records ?? [record(1, on: '2026-06-14', km: 174300)],
    items: const [],
    series: ReadingSeries.from(const [], const []),
    options: options,
    today: day('2026-09-02'),
  );
  return renderServiceReportText(
    doc,
    strings: const ServiceReportTextStrings(
      title: 'Service history',
      owned: 'Owned',
      servicesLabel: 'services',
      noRecordHeading: 'No record in this app',
      footer:
          'Generated by Odova on {date} from records kept by the owner. '
          'Not verified by a third party.',
      estimatedFootnote:
          '~ odometer estimated at the time, not read from the car.',
    ),
    formatDate: (d) => d,
    formatDistance: (d, {required estimated}) =>
        '${estimated ? '~' : ''}${d.metres ~/ 1000} km',
    formatMoney: (m) => '${m.amountMinor / 100} ${m.currency.code}',
  );
}

void main() {
  test('the vehicle and its span open the document', () {
    final text = render();

    expect(text, startsWith('VW Golf 1.6 TDI'));
    expect(text, contains('2018-03-04'));
  });

  test('the footer is there, with the generation date substituted', () {
    // §12 calls it unremovable, so it is not behind a toggle and there is no
    // parameter that removes it.
    expect(render(), contains('Not verified by a third party'));
    expect(render(), contains('2026-09-02'));
  });

  test('a plate that is toggled off never reaches the clipboard', () {
    // The clipboard is the LEAKIEST of the three renderers — it goes into a
    // public classifieds advert. A toggle honoured by the preview and the PDF
    // but not by this is the exact shape of an identity leak.
    expect(render(plate: 'M-AB 1234'), isNot(contains('M-AB 1234')));
    expect(
      render(
        plate: 'M-AB 1234',
        options: const ServiceReportOptions(plateAndVin: true),
      ),
      contains('M-AB 1234'),
    );
  });

  test('private notes are likewise off unless toggled', () {
    expect(
      render(notes: 'cheaper than the dealer wanted'),
      isNot(contains('cheaper')),
    );
  });

  test('Costs off removes every money figure, not just the totals', () {
    // A per-line amount left behind by a "hide the totals" implementation is
    // a price list the seller thought they had turned off.
    final text = render(options: const ServiceReportOptions(costs: false));

    expect(text, isNot(contains('EUR')));
    expect(text, isNot(contains('184.5')));
  });

  test('years are headed and records sit under them, newest first', () {
    final text = render(
      records: [
        record(1, on: '2026-06-14', km: 174300),
        record(2, on: '2025-02-02', km: 168110),
      ],
    );

    expect(text.indexOf('2026'), lessThan(text.indexOf('2025')));
  });

  test('an estimated odometer carries ~ and the footnote once', () {
    final text = renderServiceReportText(
      buildServiceReport(
        vehicle: Vehicle(
          id: _veh,
          name: 'Golf',
          vehicleType: VehicleType.car,
          fuelKindDefault: FuelKind.diesel,
          status: VehicleStatus.active,
          createdAtUtcMs: 1,
          updatedAtUtcMs: 1,
        ),
        records: [
          ServiceRecord(
            id: ServiceRecordId.tryParse('srv_${_b(3)}')!,
            vehicleId: _veh,
            occurredOn: '2026-06-14',
            odometer: const Distance.fromKm(174300),
            odometerUnit: DistanceUnit.km,
            odometerEstimated: true,
            lines: const [],
            createdAtUtcMs: 1,
            updatedAtUtcMs: 1,
          ),
        ],
        items: const [],
        series: ReadingSeries.from(const [], const []),
        options: const ServiceReportOptions(),
        today: day('2026-09-02'),
      ),
      strings: const ServiceReportTextStrings(
        title: 'Service history',
        owned: 'Owned',
        servicesLabel: 'services',
        noRecordHeading: 'No record in this app',
        footer: 'Generated on {date}.',
        estimatedFootnote: '~ odometer estimated at the time.',
      ),
      formatDate: (d) => d,
      formatDistance: (d, {required estimated}) =>
          '${estimated ? '~' : ''}${d.metres ~/ 1000} km',
      formatMoney: (m) => '${m.amountMinor}',
    );

    expect(text, contains('~174300 km'));
    expect(
      '~ odometer estimated at the time.'.allMatches(text).length,
      1,
    );
  });

  test('it ends with exactly one newline, whatever the toggles are', () {
    // It goes into a paste buffer, and a trailing run of blank lines is
    // visible in every classifieds text box on earth. The invariant holds
    // because the unremovable footer is always the last line written — which
    // is why there is no trim on the way out.
    for (final options in const [
      ServiceReportOptions(),
      ServiceReportOptions(costs: false, fuelSummary: false),
      ServiceReportOptions(plateAndVin: true, notes: true),
    ]) {
      final text = render(options: options);
      expect(text, endsWith('\n'), reason: '$options');
      expect(text.endsWith('\n\n'), isFalse, reason: '$options');
    }
  });
}
