// SPEC.md §12's two actions, and the states around them.
//
// "Over 200 records, generation shows a blocking 'Building your report…' with a
// Cancel instead of a frozen button; under 200 it is synchronous." The
// threshold is the interesting part: a progress dialog for work that takes
// twelve milliseconds is a flash the user reads as a fault, and a frozen button
// for work that takes two seconds is an app they force-quit.

import 'dart:io';

import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:odova/app/share/share_service.dart';
import 'package:odova/core/report/service_report_text.dart';
import 'package:odova/core/report/service_report_writer.dart';
import 'package:odova/core/result.dart';
import 'package:odova/core/time/civil_date.dart';
import 'package:odova/features/report/application/report_notifier.dart';

import '../../../support/report_fake_repository.dart';

final CivilDate _today = CivilDate.tryParse('2026-09-02')!;

/// A share port that records rather than shares.
class _FakeShare implements ShareService {
  final List<({String fileName, String mimeType, int bytes})> shared = [];
  int discards = 0;
  ShareFailure? refuseWith;

  @override
  Future<Result<void, ShareFailure>> shareFile({
    required Uint8List bytes,
    required String fileName,
    required String mimeType,
  }) async {
    final failure = refuseWith;
    if (failure != null) return Err(failure);
    shared.add((
      fileName: fileName,
      mimeType: mimeType,
      bytes: bytes.length,
    ));
    return const Ok(null);
  }

  @override
  Future<Result<void, ShareFailure>> shareWrittenFile({
    required File file,
    required String mimeType,
  }) async {
    // §12's report renders to bytes in memory and never takes this path. The
    // backup export does (EPIC-15 task 15.5); a fake that quietly returned Ok
    // here would be a fake that lies about the port it implements.
    fail('the report shares bytes, never a written file');
  }

  @override
  Future<Result<void, ShareFailure>> discard() async {
    discards++;
    return const Ok(null);
  }
}

/// The recording port the container is built around.
///
/// Typed as the fake rather than `ShareService` on purpose: the assertions are
/// about what it RECORDED, and the interface has no `shared` list to read.
// ignore: library_private_types_in_public_api
late _FakeShare share;

ProviderContainer _container({int services = 3}) {
  share = _FakeShare();
  final container = ProviderContainer(
    overrides: [
      reportRepositoryProvider.overrideWithValue(
        FakeReportRepository(serviceCount: services),
      ),
      shareServiceProvider.overrideWithValue(share),
    ],
  );
  addTearDown(container.dispose);
  return container;
}

Future<ReportNotifier> _loaded(ProviderContainer c) async {
  final n = c.read(reportProvider.notifier)
    ..ensureLoaded('veh_1', today: _today);
  await Future<void>.delayed(Duration.zero);
  return n;
}

/// Stand-ins for the app's real formatters. The mark is placed by the
/// FORMATTER, mirroring `formatDistanceFigure` — a fake that concatenated it
/// here would pass against the bug `check_status_encoding.sh` catches.
final ReportFormatters _formatters = ReportFormatters(
  date: (d) => d,
  distance: (d, {required estimated}) =>
      '${estimated ? '~' : ''}${d.metres ~/ 1000} km',
  money: (m) => '${m.amountMinor}',
  number: (n, {required grouped}) => n.toString(),
);

const ServiceReportPdfStrings _pdfStrings = ServiceReportPdfStrings(
  title: 'Service history',
  pageOf: 'Page {n} of {total}',
  columnDate: 'Date',
  columnOdometer: 'Odometer',
  columnWork: 'What was done',
  columnCost: 'Cost',
  footer: 'Generated by Odova on {date} ({iso}).',
  estimatedFootnote: '~ odometer estimated at the time.',
);

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  setUp(() {
    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(kShareChannel, (_) async => null);
  });

  test("sharing writes a PDF with §12's filename and mime type", () async {
    final container = _container();
    final notifier = await _loaded(container);

    await notifier.sharePdf(
      vehicleName: 'VW Golf',
      positionalIndex: 1,
      strings: _pdfStrings,
      formatters: _formatters,
      rtl: false,
    );

    expect(share.shared, hasLength(1));
    expect(
      share.shared.single.fileName,
      'odova-service-history-vw-golf-2026-09-02.pdf',
    );
    expect(share.shared.single.mimeType, 'application/pdf');
    expect(share.shared.single.bytes, greaterThan(500), reason: 'a real PDF');
  });

  test(
    'a name that transliterates to nothing gets the positional fallback',
    () async {
      final container = _container();
      final notifier = await _loaded(container);

      await notifier.sharePdf(
        vehicleName: 'پژو ۲۰۶',
        positionalIndex: 2,
        strings: _pdfStrings,
        formatters: _formatters,
        // A Persian name, so the document mirrors. `rtl` is a required
        // parameter and not a field on the notifier: as a field it was never
        // assigned anywhere in `lib/`, so every fa/ar/ckb user would have got
        // an LTR PDF and nothing would have said so.
        rtl: true,
      );

      expect(
        share.shared.single.fileName,
        'odova-service-history-vehicle-2-2026-09-02.pdf',
      );
    },
  );

  test('under 200 records it never shows the blocking progress', () async {
    // §12's threshold. The state is asserted AFTER the await, so this would
    // pass against an implementation that set and cleared it — which is why
    // the next test watches it during.
    final container = _container();
    final notifier = await _loaded(container);

    await notifier.sharePdf(
      vehicleName: 'Golf',
      positionalIndex: 1,
      strings: _pdfStrings,
      formatters: _formatters,
      rtl: false,
    );

    expect(container.read(reportProvider).isBuilding, isFalse);
  });

  test('over 200 records it DOES show it, and clears it after', () async {
    final container = _container(services: 400);
    final notifier = await _loaded(container);

    final pending = notifier.sharePdf(
      vehicleName: 'Golf',
      positionalIndex: 1,
      strings: _pdfStrings,
      formatters: _formatters,
      rtl: false,
    );
    expect(
      container.read(reportProvider).isBuilding,
      isTrue,
      reason: 'while it is building, not only after',
    );

    await pending;
    expect(container.read(reportProvider).isBuilding, isFalse);
  });

  test('a refusal is a code on the state, never a throw', () async {
    // §12 renders it inline under the button with Try again. A thrown
    // exception is a red screen instead.
    final container = _container();
    final notifier = await _loaded(container);
    share.refuseWith = const ShareFailure('share_write');

    await notifier.sharePdf(
      vehicleName: 'Golf',
      positionalIndex: 1,
      strings: _pdfStrings,
      formatters: _formatters,
      rtl: false,
    );

    expect(container.read(reportProvider).shareFailureCode, 'share_write');
  });

  test('a retry clears the previous failure before it starts', () async {
    // Otherwise the error from the last attempt sits under the button while
    // the new one succeeds, and the user believes it failed twice.
    final container = _container();
    final notifier = await _loaded(container);
    share.refuseWith = const ShareFailure('share_write');
    await notifier.sharePdf(
      vehicleName: 'Golf',
      positionalIndex: 1,
      strings: _pdfStrings,
      formatters: _formatters,
      rtl: false,
    );

    share.refuseWith = null;
    await notifier.sharePdf(
      vehicleName: 'Golf',
      positionalIndex: 1,
      strings: _pdfStrings,
      formatters: _formatters,
      rtl: false,
    );

    expect(container.read(reportProvider).shareFailureCode, isNull);
  });

  test('cancelling abandons generation and deletes the temp file', () async {
    // §12's Cancel. A cancelled report that leaves a copy of somebody's
    // service history in a cache is the leak §2 exists to prevent.
    final container = _container(services: 400);
    final notifier = await _loaded(container);

    await notifier.cancelShare();

    expect(share.discards, greaterThan(0));
    expect(container.read(reportProvider).isBuilding, isFalse);
  });

  test('Copy as text puts the same document on the clipboard', () async {
    final container = _container();
    final notifier = await _loaded(container);

    final copied = <MethodCall>[];
    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(SystemChannels.platform, (call) async {
          if (call.method == 'Clipboard.setData') copied.add(call);
          return null;
        });

    await notifier.copyAsText(
      strings: const ServiceReportTextStrings(
        title: 'Service history',
        owned: 'Owned',
        servicesLabel: 'services',
        noRecordHeading: 'No record in this app',
        footer: 'Generated on {date}.',
        estimatedFootnote: '~ estimated.',
      ),
      formatters: _formatters,
    );

    expect(copied, hasLength(1));
    final text =
        (copied.single.arguments as Map<Object?, Object?>)['text']! as String;
    expect(text, contains('The Golf'));
    expect(text, contains('Generated on 2026-09-02.'));
  });
}
