// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    vehicles,
    serviceItems,
    settings,
    serviceRecords,
    serviceLines,
    trips,
    fillUps,
    expenses,
    odometerReadings,
    odometerCorrections,
    scheduledNotifications,
  ];
  late final Shape0 vehicles = Shape0(
    source: i0.VersionedTable(
      entityName: 'vehicles',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 serviceItems = Shape1(
    source: i0.VersionedTable(
      entityName: 'service_items',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_31,
        _column_32,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 settings = Shape2(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_52,
        _column_1,
        _column_2,
        _column_3,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_31,
        _column_32,
        _column_64,
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_73,
        _column_74,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 serviceRecords = Shape3(
    source: i0.VersionedTable(
      entityName: 'service_records',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_33,
        _column_75,
        _column_76,
        _column_77,
        _column_78,
        _column_79,
        _column_80,
        _column_81,
        _column_82,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 serviceLines = Shape4(
    source: i0.VersionedTable(
      entityName: 'service_lines',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_83,
        _column_84,
        _column_85,
        _column_86,
        _column_87,
        _column_88,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 trips = Shape5(
    source: i0.VersionedTable(
      entityName: 'trips',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_33,
        _column_89,
        _column_90,
        _column_91,
        _column_92,
        _column_93,
        _column_94,
        _column_95,
        _column_77,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 fillUps = Shape6(
    source: i0.VersionedTable(
      entityName: 'fill_ups',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_33,
        _column_75,
        _column_76,
        _column_77,
        _column_96,
        _column_97,
        _column_98,
        _column_99,
        _column_100,
        _column_101,
        _column_87,
        _column_102,
        _column_103,
        _column_104,
        _column_105,
        _column_106,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 expenses = Shape7(
    source: i0.VersionedTable(
      entityName: 'expenses',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_33,
        _column_106,
        _column_75,
        _column_107,
        _column_35,
        _column_108,
        _column_87,
        _column_109,
        _column_110,
        _column_76,
        _column_77,
        _column_80,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 odometerReadings = Shape8(
    source: i0.VersionedTable(
      entityName: 'odometer_readings',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_33,
        _column_75,
        _column_111,
        _column_77,
        _column_112,
        _column_113,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 odometerCorrections = Shape9(
    source: i0.VersionedTable(
      entityName: 'odometer_corrections',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_33,
        _column_114,
        _column_115,
        _column_116,
        _column_77,
        _column_117,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 scheduledNotifications = Shape10(
    source: i0.VersionedTable(
      entityName: 'scheduled_notifications',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: [
        'PRIMARY KEY("key")',
        'CHECK(state IN (\'pending\', \'fired\', \'dropped\', \'cancelled\'))',
        'CHECK(stage IN (\'early\', \'due\', \'overdue1\', \'overdue2\', \'nudge\'))',
        'CHECK(fire_at_local GLOB \'[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]\')',
        'CHECK(os_id >= 0 AND os_id < 2147483648)',
        'CHECK(length(fire_at_local) = 16)',
      ],
      columns: [
        _column_118,
        _column_119,
        _column_120,
        _column_121,
        _column_122,
        _column_123,
        _column_124,
        _column_125,
        _column_2,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAtUtcMs =>
      columnsByName['created_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAtUtcMs =>
      columnsByName['updated_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAtUtcMs =>
      columnsByName['deleted_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get make =>
      columnsByName['make']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get model =>
      columnsByName['model']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get year =>
      columnsByName['year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get plate =>
      columnsByName['plate']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get vin =>
      columnsByName['vin']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get vehicleType =>
      columnsByName['vehicle_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isBusiness =>
      columnsByName['is_business']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get fuelKindDefault =>
      columnsByName['fuel_kind_default']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get tankCapacityMl =>
      columnsByName['tank_capacity_ml']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get purchaseDate =>
      columnsByName['purchase_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get purchaseOdometerM =>
      columnsByName['purchase_odometer_m']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get purchasePriceMinor =>
      columnsByName['purchase_price_minor']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get purchasePriceCurrency =>
      columnsByName['purchase_price_currency']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get soldOn =>
      columnsByName['sold_on']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get soldPriceMinor =>
      columnsByName['sold_price_minor']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get soldPriceCurrency =>
      columnsByName['sold_price_currency']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get expectedAnnualM =>
      columnsByName['expected_annual_m']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get colour =>
      columnsByName['colour']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get notificationsMuted =>
      columnsByName['notifications_muted']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get currency =>
      columnsByName['currency']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get distanceUnit =>
      columnsByName['distance_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get volumeUnit =>
      columnsByName['volume_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get consumptionUnit =>
      columnsByName['consumption_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get noticeDistanceM =>
      columnsByName['notice_distance_m']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get noticeDays =>
      columnsByName['notice_days']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_1(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at_utc_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_2(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at_utc_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'deleted_at_utc_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'make',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'model',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'year',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'plate',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'vin',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_10(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'vehicle_type',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL CHECK (vehicle_type IN (\'car\', \'van\', \'motorcycle\', \'truck\', \'other\'))',
);
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_business',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_business IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_12(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'fuel_kind_default',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL CHECK (fuel_kind_default IN (\'petrol\', \'diesel\', \'lpg\', \'cng\', \'electric\', \'hybrid\', \'other\'))',
);
i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'tank_capacity_ml',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'CHECK (tank_capacity_ml IS NULL OR tank_capacity_ml > 0)',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'purchase_date',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'purchase_odometer_m',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'purchase_price_minor',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_17(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'purchase_price_currency',
  aliasedName,
  true,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'CHECK (purchase_price_currency IS NULL OR length(purchase_price_currency) = 3)',
);
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL CHECK (status IN (\'active\', \'archived\', \'sold\'))',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sold_on',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sold_price_minor',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_21(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'sold_price_currency',
  aliasedName,
  true,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'CHECK (sold_price_currency IS NULL OR length(sold_price_currency) = 3)',
);
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'expected_annual_m',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'colour',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'notes',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sort_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'notifications_muted',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (notifications_muted IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'currency',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'CHECK (currency IS NULL OR length(currency) = 3)',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'distance_unit',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'CHECK (distance_unit IN (\'km\', \'mi\'))',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'volume_unit',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'CHECK (volume_unit IN (\'l\', \'gal_us\', \'gal_uk\'))',
    );
i1.GeneratedColumn<String> _column_30(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'consumption_unit',
  aliasedName,
  true,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'CHECK (consumption_unit IN (\'l_100km\', \'km_l\', \'mpg_us\', \'mpg_uk\', \'kwh_100km\', \'mi_kwh\'))',
);
i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'notice_distance_m',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'notice_days',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAtUtcMs =>
      columnsByName['created_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAtUtcMs =>
      columnsByName['updated_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAtUtcMs =>
      columnsByName['deleted_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get vehicleId =>
      columnsByName['vehicle_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get label =>
      columnsByName['label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get intervalDistanceM =>
      columnsByName['interval_distance_m']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get intervalDistanceUnit =>
      columnsByName['interval_distance_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get intervalMonths =>
      columnsByName['interval_months']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get targetOdometerM =>
      columnsByName['target_odometer_m']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get targetDate =>
      columnsByName['target_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get baselineDate =>
      columnsByName['baseline_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get baselineOdometerM =>
      columnsByName['baseline_odometer_m']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get noticeDistanceM =>
      columnsByName['notice_distance_m']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get noticeDays =>
      columnsByName['notice_days']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isTracked =>
      columnsByName['is_tracked']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isActive =>
      columnsByName['is_active']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get notify =>
      columnsByName['notify']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get priority =>
      columnsByName['priority']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rollover =>
      columnsByName['rollover']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get repeats =>
      columnsByName['repeats']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get snoozedUntil =>
      columnsByName['snoozed_until']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get snoozeUntilOdometerM =>
      columnsByName['snooze_until_odometer_m']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get snoozeCount =>
      columnsByName['snooze_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'vehicle_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES vehicles(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_34(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'kind',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL CHECK (kind IN (\'oil_and_filter\', \'air_filter\', \'cabin_filter\', \'fuel_filter\', \'spark_plugs\', \'timing_belt\', \'brake_pads_check\', \'brake_pads_front\', \'brake_pads_rear\', \'brake_fluid\', \'coolant\', \'transmission_fluid\', \'wheel_alignment\', \'tyre_rotate\', \'tyre_replace\', \'battery\', \'wipers\', \'inspection\', \'registration\', \'insurance_renewal\', \'ac_service\', \'chain_lube\', \'chain_and_sprockets\', \'valve_clearance\', \'fork_oil\', \'reduction_gearbox_oil\', \'battery_12v\', \'custom\'))',
);
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'label',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_36(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'interval_distance_m',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'CHECK (interval_distance_m IS NULL OR interval_distance_m > 0)',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'interval_distance_unit',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'CHECK (interval_distance_unit IN (\'km\', \'mi\'))',
    );
i1.GeneratedColumn<int> _column_38(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'interval_months',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'CHECK (interval_months IS NULL OR interval_months > 0)',
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'target_odometer_m',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'target_date',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'baseline_date',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_42(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'baseline_odometer_m',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_tracked',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_tracked IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_44(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_active',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_45(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'notify',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (notify IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'priority',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL CHECK (priority IN (\'safety\', \'normal\', \'low\'))',
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'rollover',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL CHECK (rollover IN (\'from_actual\', \'from_due\'))',
    );
i1.GeneratedColumn<int> _column_48(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'repeats',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (repeats IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'snoozed_until',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_50(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'snooze_until_odometer_m',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_51(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'snooze_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAtUtcMs =>
      columnsByName['created_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAtUtcMs =>
      columnsByName['updated_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAtUtcMs =>
      columnsByName['deleted_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get schemaVersion =>
      columnsByName['schema_version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get language =>
      columnsByName['language']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get calendar =>
      columnsByName['calendar']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get numerals =>
      columnsByName['numerals']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get firstDayOfWeek =>
      columnsByName['first_day_of_week']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get theme =>
      columnsByName['theme']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get currencyDefault =>
      columnsByName['currency_default']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get currencyDisplay =>
      columnsByName['currency_display']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get distanceUnit =>
      columnsByName['distance_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get volumeUnit =>
      columnsByName['volume_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get consumptionUnit =>
      columnsByName['consumption_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get noticeDistanceM =>
      columnsByName['notice_distance_m']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get noticeDays =>
      columnsByName['notice_days']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get notificationTimeMinutes =>
      columnsByName['notification_time_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get quietHoursFromMinutes =>
      columnsByName['quiet_hours_from_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get quietHoursToMinutes =>
      columnsByName['quiet_hours_to_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get weekdaysOnly =>
      columnsByName['weekdays_only']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get notifyService =>
      columnsByName['notify_service']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get notifyOdometer =>
      columnsByName['notify_odometer']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get notifyBackup =>
      columnsByName['notify_backup']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get activeVehicleId =>
      columnsByName['active_vehicle_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get onboardingDone =>
      columnsByName['onboarding_done']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastBackupAtUtcMs =>
      columnsByName['last_backup_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastBackupReminderAtUtcMs =>
      columnsByName['last_backup_reminder_at_utc_ms']!
          as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (id = \'settings\')',
    );
i1.GeneratedColumn<int> _column_53(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'schema_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_54(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'language',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL CHECK (language IN (\'system\', \'en\', \'de\', \'fr\', \'fa\', \'ar\', \'ckb\'))',
);
i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'calendar',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL CHECK (calendar IN (\'gregorian\', \'persian\'))',
    );
i1.GeneratedColumn<String> _column_56(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'numerals',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL CHECK (numerals IN (\'auto\', \'latin\', \'arabic_indic\', \'extended_arabic_indic\'))',
);
i1.GeneratedColumn<int> _column_57(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'first_day_of_week',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (first_day_of_week BETWEEN 1 AND 7)',
    );
i1.GeneratedColumn<String> _column_58(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'theme',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL CHECK (theme IN (\'system\', \'light\', \'dark\'))',
    );
i1.GeneratedColumn<String> _column_59(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'currency_default',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (length(currency_default) = 3)',
    );
i1.GeneratedColumn<String> _column_60(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'currency_display',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL CHECK (currency_display IN (\'none\', \'toman\'))',
    );
i1.GeneratedColumn<String> _column_61(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'distance_unit',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (distance_unit IN (\'km\', \'mi\'))',
    );
i1.GeneratedColumn<String> _column_62(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'volume_unit',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL CHECK (volume_unit IN (\'l\', \'gal_us\', \'gal_uk\'))',
    );
i1.GeneratedColumn<String> _column_63(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'consumption_unit',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL CHECK (consumption_unit IN (\'l_100km\', \'km_l\', \'mpg_us\', \'mpg_uk\', \'kwh_100km\', \'mi_kwh\'))',
);
i1.GeneratedColumn<int> _column_64(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'notification_time_minutes',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL CHECK (notification_time_minutes BETWEEN 0 AND 1439)',
    );
i1.GeneratedColumn<int> _column_65(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'quiet_hours_from_minutes',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL CHECK (quiet_hours_from_minutes BETWEEN 0 AND 1439)',
    );
i1.GeneratedColumn<int> _column_66(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'quiet_hours_to_minutes',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL CHECK (quiet_hours_to_minutes BETWEEN 0 AND 1439)',
    );
i1.GeneratedColumn<int> _column_67(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'weekdays_only',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (weekdays_only IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_68(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'notify_service',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (notify_service IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_69(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'notify_odometer',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 1 CHECK (notify_odometer IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_70(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'notify_backup',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (notify_backup IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<String> _column_71(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'active_vehicle_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_72(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'onboarding_done',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (onboarding_done IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_73(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_backup_at_utc_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_74(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_backup_reminder_at_utc_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAtUtcMs =>
      columnsByName['created_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAtUtcMs =>
      columnsByName['updated_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAtUtcMs =>
      columnsByName['deleted_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get vehicleId =>
      columnsByName['vehicle_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get occurredOn =>
      columnsByName['occurred_on']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get odometerM =>
      columnsByName['odometer_m']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get odometerUnit =>
      columnsByName['odometer_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get odometerEstimated =>
      columnsByName['odometer_estimated']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get costEstimated =>
      columnsByName['cost_estimated']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get vendor =>
      columnsByName['vendor']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get invoiceRef =>
      columnsByName['invoice_ref']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get warrantyUntil =>
      columnsByName['warranty_until']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_75(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'occurred_on',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL CHECK (occurred_on GLOB \'[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]\')',
);
i1.GeneratedColumn<int> _column_76(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'odometer_m',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'CHECK (odometer_m IS NULL OR odometer_m >= 0)',
    );
i1.GeneratedColumn<String> _column_77(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'odometer_unit',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (odometer_unit IN (\'km\', \'mi\'))',
    );
i1.GeneratedColumn<int> _column_78(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'odometer_estimated',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (odometer_estimated IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_79(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cost_estimated',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (cost_estimated IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_80(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'vendor',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_81(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'invoice_ref',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_82(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'warranty_until',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get serviceRecordId =>
      columnsByName['service_record_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get serviceItemId =>
      columnsByName['service_item_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get label =>
      columnsByName['label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get amountMinor =>
      columnsByName['amount_minor']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get currency =>
      columnsByName['currency']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get partNumber =>
      columnsByName['part_number']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_83(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'service_record_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES service_records(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_84(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'service_item_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'REFERENCES service_items(id)ON DELETE SET NULL',
    );
i1.GeneratedColumn<String> _column_85(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'label',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_86(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'amount_minor',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (amount_minor >= 0)',
    );
i1.GeneratedColumn<String> _column_87(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'currency',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (length(currency) = 3)',
    );
i1.GeneratedColumn<String> _column_88(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'part_number',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAtUtcMs =>
      columnsByName['created_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAtUtcMs =>
      columnsByName['updated_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAtUtcMs =>
      columnsByName['deleted_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get vehicleId =>
      columnsByName['vehicle_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get purpose =>
      columnsByName['purpose']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get startedOn =>
      columnsByName['started_on']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get endedOn =>
      columnsByName['ended_on']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startOdometerM =>
      columnsByName['start_odometer_m']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endOdometerM =>
      columnsByName['end_odometer_m']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get manualDistanceM =>
      columnsByName['manual_distance_m']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get odometerUnit =>
      columnsByName['odometer_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_89(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_90(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'purpose',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL CHECK (purpose IN (\'business\', \'commute\', \'personal\', \'other\'))',
);
i1.GeneratedColumn<String> _column_91(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'started_on',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL CHECK (started_on GLOB \'[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]\')',
);
i1.GeneratedColumn<String> _column_92(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ended_on',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_93(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'start_odometer_m',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_94(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'end_odometer_m',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_95(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'manual_distance_m',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'CHECK (manual_distance_m IS NULL OR manual_distance_m >= 0)',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAtUtcMs =>
      columnsByName['created_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAtUtcMs =>
      columnsByName['updated_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAtUtcMs =>
      columnsByName['deleted_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get vehicleId =>
      columnsByName['vehicle_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get occurredOn =>
      columnsByName['occurred_on']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get odometerM =>
      columnsByName['odometer_m']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get odometerUnit =>
      columnsByName['odometer_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fuelKind =>
      columnsByName['fuel_kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get quantityMl =>
      columnsByName['quantity_ml']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get quantityG =>
      columnsByName['quantity_g']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get energyWh =>
      columnsByName['energy_wh']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get quantityUnit =>
      columnsByName['quantity_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get totalCostMinor =>
      columnsByName['total_cost_minor']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get currency =>
      columnsByName['currency']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isFullTank =>
      columnsByName['is_full_tank']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get chainBroken =>
      columnsByName['chain_broken']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get grade =>
      columnsByName['grade']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get station =>
      columnsByName['station']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tripId =>
      columnsByName['trip_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_96(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'fuel_kind',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL CHECK (fuel_kind IN (\'petrol\', \'diesel\', \'lpg\', \'cng\', \'electric\', \'hybrid\', \'other\'))',
);
i1.GeneratedColumn<int> _column_97(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'quantity_ml',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'CHECK (quantity_ml IS NULL OR quantity_ml > 0)',
    );
i1.GeneratedColumn<int> _column_98(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'quantity_g',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'CHECK (quantity_g IS NULL OR quantity_g > 0)',
    );
i1.GeneratedColumn<int> _column_99(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'energy_wh',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'CHECK (energy_wh IS NULL OR energy_wh > 0)',
    );
i1.GeneratedColumn<String> _column_100(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'quantity_unit',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL CHECK (quantity_unit IN (\'l\', \'gal_us\', \'gal_uk\'))',
    );
i1.GeneratedColumn<int> _column_101(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'total_cost_minor',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (total_cost_minor >= 0)',
    );
i1.GeneratedColumn<int> _column_102(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_full_tank',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (is_full_tank IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_103(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'chain_broken',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (chain_broken IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_104(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'grade',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_105(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'station',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_106(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'trip_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'REFERENCES trips(id)ON DELETE SET NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAtUtcMs =>
      columnsByName['created_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAtUtcMs =>
      columnsByName['updated_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAtUtcMs =>
      columnsByName['deleted_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get vehicleId =>
      columnsByName['vehicle_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tripId =>
      columnsByName['trip_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get occurredOn =>
      columnsByName['occurred_on']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get category =>
      columnsByName['category']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get label =>
      columnsByName['label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get amountMinor =>
      columnsByName['amount_minor']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get currency =>
      columnsByName['currency']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get coversFrom =>
      columnsByName['covers_from']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get coversTo =>
      columnsByName['covers_to']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get odometerM =>
      columnsByName['odometer_m']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get odometerUnit =>
      columnsByName['odometer_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get vendor =>
      columnsByName['vendor']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_107(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'category',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL CHECK (category IN (\'insurance\', \'tax_registration\', \'parking\', \'toll\', \'fine\', \'wash\', \'tyre_storage\', \'accessories\', \'finance\', \'other\'))',
);
i1.GeneratedColumn<int> _column_108(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'amount_minor',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_109(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'covers_from',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_110(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'covers_to',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAtUtcMs =>
      columnsByName['created_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAtUtcMs =>
      columnsByName['updated_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAtUtcMs =>
      columnsByName['deleted_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get vehicleId =>
      columnsByName['vehicle_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get occurredOn =>
      columnsByName['occurred_on']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get odometerM =>
      columnsByName['odometer_m']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get odometerUnit =>
      columnsByName['odometer_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceId =>
      columnsByName['source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_111(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'odometer_m',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (odometer_m >= 0)',
    );
i1.GeneratedColumn<String> _column_112(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'source',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL CHECK (source IN (\'manual\', \'fillup\', \'service\', \'expense\', \'trip_start\', \'trip_end\', \'import\'))',
);
i1.GeneratedColumn<String> _column_113(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAtUtcMs =>
      columnsByName['created_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAtUtcMs =>
      columnsByName['updated_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAtUtcMs =>
      columnsByName['deleted_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get vehicleId =>
      columnsByName['vehicle_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fromReadingId =>
      columnsByName['from_reading_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get previousM =>
      columnsByName['previous_m']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get newM =>
      columnsByName['new_m']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get odometerUnit =>
      columnsByName['odometer_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get reason =>
      columnsByName['reason']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_114(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'from_reading_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES odometer_readings(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_115(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'previous_m',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (previous_m >= 0)',
    );
i1.GeneratedColumn<int> _column_116(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'new_m',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (new_m >= 0)',
    );
i1.GeneratedColumn<String> _column_117(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'reason',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL CHECK (reason IN (\'cluster_replaced\', \'rollover\', \'typo_fix\'))',
);

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get osId =>
      columnsByName['os_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get vehicleId =>
      columnsByName['vehicle_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get reminderId =>
      columnsByName['reminder_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get stage =>
      columnsByName['stage']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fireAtLocal =>
      columnsByName['fire_at_local']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bodyHash =>
      columnsByName['body_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get state =>
      columnsByName['state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAtUtcMs =>
      columnsByName['updated_at_utc_ms']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_118(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_119(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'os_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_120(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'vehicle_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_121(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'reminder_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_122(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'stage',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_123(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'fire_at_local',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_124(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'body_hash',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_125(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
