// Regenerates the fuel engine's golden vectors.
//
// SPEC.md §17's definition of done names nine cases the fuel engine must pass.
// This writes them as a file a reviewer can READ — inputs beside expected
// outputs, one entry per case — rather than as assertions buried in a test.
//
//   dart run tools/regen_fuel_vectors.dart          # write
//   dart run tools/regen_fuel_vectors.dart --check  # fail if it would change
//
// The `--check` mode is the gate: it proves the committed file was generated by
// this code and not hand-edited into agreement with a bug. A vector edited by
// hand to match a wrong answer is worse than no vector at all, because it
// carries the authority of a golden file.
//
// Synthetic fills only. CLAUDE.md forbids committing a real backup as a
// fixture, and the file is named `*.fixture.json` for that reason.
import 'dart:convert';
import 'dart:io';

import 'package:odova/core/fuel/build_fuel_segments.dart';
import 'package:odova/core/fuel/consumption_stats.dart';
import 'package:odova/core/fuel/fuel_result.dart';
import 'package:odova/core/units/consumption.dart';
import 'package:odova/core/units/energy.dart';
import 'package:odova/core/units/fuel_quantity.dart';
import 'package:odova/core/units/volume.dart';

const _path = 'test/fixtures/fuel/fuel_vectors.fixture.json';

/// One case: a name, some fills, and what the engine should say about them.
typedef Vector = ({String id, String why, List<FillUpPoint> fills});

FillUpPoint _fill(
  String id, {
  required int? km,
  required int millilitres,
  required String on,
  bool full = true,
  bool broken = false,
  String kind = 'diesel',
}) => (
  id: id,
  occurredOn: on,
  createdAtUtcMs: 0,
  fuelKind: kind,
  cumulativeM: km == null ? null : km * 1000,
  quantity: LiquidVolume(Volume(millilitres)),
  isFullTank: full,
  chainBroken: broken,
  tankCapacityMl: null,
);

FillUpPoint _charge(
  String id, {
  required int km,
  required int wattHours,
  required String on,
  bool full = true,
}) => (
  id: id,
  occurredOn: on,
  createdAtUtcMs: 0,
  fuelKind: 'electric',
  cumulativeM: km * 1000,
  quantity: ElectricEnergy(Energy(wattHours)),
  isFullTank: full,
  chainBroken: false,
  tankCapacityMl: null,
);

/// The nine cases SPEC.md §17 names, plus the total-over-total one it calls out
/// separately. Each id is asserted by name in the test, so the gate cannot
/// quietly shrink.
List<Vector> vectors() => [
  (
    id: 'first_fill',
    why: 'One fill opens a segment and produces nothing, ever.',
    fills: [_fill('a', km: 0, millilitres: 40000, on: '2026-01-01')],
  ),
  (
    id: 'partials',
    why: 'Two partials join the enclosing segment; neither opens or closes.',
    fills: [
      _fill('a', km: 0, millilitres: 40000, on: '2026-01-01'),
      _fill('b', km: 200, millilitres: 15000, on: '2026-01-10', full: false),
      _fill('c', km: 400, millilitres: 20000, on: '2026-01-20', full: false),
      _fill('d', km: 600, millilitres: 10000, on: '2026-02-01'),
    ],
  ),
  (
    id: 'chain_broken',
    why: 'The segment that would have closed is discarded, not averaged.',
    fills: [
      _fill('a', km: 0, millilitres: 40000, on: '2026-01-01'),
      _fill('b', km: 600, millilitres: 45000, on: '2026-02-01', broken: true),
      _fill('c', km: 1200, millilitres: 50000, on: '2026-03-01'),
    ],
  ),
  (
    id: 'missing_odometer_import',
    why: 'An imported row with no reading is a chain break.',
    fills: [
      _fill('a', km: 0, millilitres: 40000, on: '2026-01-01'),
      _fill('b', km: null, millilitres: 45000, on: '2026-02-01'),
      _fill('c', km: 1200, millilitres: 50000, on: '2026-03-01'),
    ],
  ),
  (
    id: 'zero_distance',
    why: 'Two fills at the same odometer: both flagged, never a 0 L/100 km.',
    fills: [
      _fill('a', km: 600, millilitres: 40000, on: '2026-01-01'),
      _fill('b', km: 600, millilitres: 45000, on: '2026-02-01'),
    ],
  ),
  (
    id: 'negative_distance',
    why: 'A backwards odometer: both flagged, nothing emitted.',
    fills: [
      _fill('a', km: 600, millilitres: 40000, on: '2026-01-01'),
      _fill('b', km: 500, millilitres: 45000, on: '2026-02-01'),
    ],
  ),
  (
    id: 'bi_fuel',
    why: 'Two independent series; an LPG fill is not a petrol chain break.',
    fills: [
      _fill('p1', km: 0, millilitres: 40000, on: '2026-01-01', kind: 'petrol'),
      _fill('l1', km: 300, millilitres: 30000, on: '2026-01-15', kind: 'lpg'),
      _fill(
        'p2',
        km: 600,
        millilitres: 45000,
        on: '2026-02-01',
        kind: 'petrol',
      ),
      _fill('l2', km: 900, millilitres: 35000, on: '2026-02-15', kind: 'lpg'),
    ],
  ),
  (
    id: 'ev_with_full_charges',
    why: 'Identical rules on watt-hours.',
    fills: [
      _charge('a', km: 0, wattHours: 50000, on: '2026-01-01'),
      _charge('b', km: 300, wattHours: 52000, on: '2026-02-01'),
    ],
  ),
  (
    id: 'ev_without_full_charges',
    why: 'No full charge, so no energy figure is invented from partials.',
    fills: [
      _charge('a', km: 0, wattHours: 30000, on: '2026-01-01', full: false),
      _charge('b', km: 300, wattHours: 32000, on: '2026-02-01', full: false),
    ],
  ),
  (
    id: 'lifetime_total_over_total',
    why:
        'A short thirsty tank and a long lean one. The mean is 9.0; the '
        'average is 6.26.',
    fills: [
      _fill('a', km: 0, millilitres: 40000, on: '2026-01-01'),
      _fill('b', km: 40, millilitres: 4800, on: '2026-01-05'),
      _fill('c', km: 940, millilitres: 54000, on: '2026-03-01'),
    ],
  ),
];

/// The engine's answer for one vector, as plain JSON.
Map<String, Object?> evaluate(Vector vector) {
  final byKind = buildFuelSegmentsByKind(vector.fills);

  return {
    'id': vector.id,
    'why': vector.why,
    'fills': [
      for (final fill in vector.fills)
        {
          'id': fill.id,
          'occurred_on': fill.occurredOn,
          'fuel_kind': fill.fuelKind,
          'cumulative_m': fill.cumulativeM,
          'quantity': _quantityJson(fill.quantity),
          'is_full_tank': fill.isFullTank,
          'chain_broken': fill.chainBroken,
        },
    ],
    'expected': {
      for (final entry in byKind.entries)
        entry.key: {
          'segments': [
            for (final segment in entry.value.segments)
              {
                'from': segment.fromFillUpId,
                'to': segment.toFillUpId,
                'distance_m': segment.distance.metres,
                'quantity': _quantityJson(segment.quantity),
                'partial_count': segment.partialCount,
                'l_per_100km': _round(
                  segment.consumption.asUnit(ConsumptionUnit.lPer100km),
                ),
                'kwh_per_100km': _round(
                  segment.consumption.asUnit(ConsumptionUnit.kwhPer100km),
                ),
              },
          ],
          'flagged': entry.value.flaggedFillUpIds,
          'average': _averageJson(entry.value.segments),
        },
    },
  };
}

Map<String, Object?> _averageJson(List<dynamic> segments) {
  final average = averageConsumption(segments.cast());
  return switch (average) {
    Computed(:final value) => {
      'l_per_100km': _round(value.asUnit(ConsumptionUnit.lPer100km)),
      'kwh_per_100km': _round(value.asUnit(ConsumptionUnit.kwhPer100km)),
    },
    Unavailable(:final reason) => {'unavailable': reason.code},
  };
}

Map<String, Object?> _quantityJson(FuelQuantity quantity) => switch (quantity) {
  LiquidVolume(:final volume) => {'ml': volume.millilitres},
  GasMass(:final mass) => {'g': mass.grams},
  ElectricEnergy(:final energy) => {'wh': energy.wattHours},
};

/// Six decimals, so the file is stable across platforms.
///
/// A raw double's last bits differ between architectures and the `--check`
/// gate would then fail for the machine rather than for the code.
double? _round(double? value) =>
    value == null ? null : double.parse(value.toStringAsFixed(6));

String render() =>
    '${const JsonEncoder.withIndent('  ').convert({
      '_generated_by': 'tools/regen_fuel_vectors.dart',
      '_spec': "SPEC.md §17's fuel fixture suite",
      'vectors': [for (final vector in vectors()) evaluate(vector)],
    })}\n';

void main(List<String> args) {
  final file = File(_path);
  final rendered = render();

  if (args.contains('--check')) {
    if (!file.existsSync()) {
      stderr.writeln('FAIL  $_path does not exist');
      exit(1);
    }
    if (file.readAsStringSync() != rendered) {
      stderr.writeln(
        'FAIL  $_path differs from what the generator produces.\n'
        '      Either the engine changed and the vectors need regenerating,\n'
        '      or the file was hand-edited — which is worse, because a vector\n'
        '      edited to match a bug carries the authority of a golden file.\n'
        '      Run: dart run tools/regen_fuel_vectors.dart',
      );
      exit(1);
    }
    stdout.writeln('ok    $_path matches the generator');
    return;
  }

  file
    ..createSync(recursive: true)
    ..writeAsStringSync(rendered);
  stdout.writeln('wrote $_path');
}
